---
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
matrix:
  include:
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 3.0"
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 3.0"
    - rvm: 2.1.5
      env: PUPPET_GEM_VERSION="~> 3.0"
    - rvm: 2.1.5
      env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
    - rvm: 2.1.6
      env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
notifications:
  email: false
